# Generated by Django 4.0.4 on 2022-04-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('Description', models.CharField(max_length=500, verbose_name='Title')),
                ('File', models.FileField(default=None, max_length=250, null=True, upload_to='file/')),
            ],
        ),
    ]
