# Generated by Django 4.0.4 on 2022-04-24 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0002_remove_data_title_data_user_alter_data_description'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='data',
        #     name='title',
        #     field=models.CharField(default=1, max_length=100, unique=True),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='data',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
